### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by jpcozar** [JurajNyiri/HomeAssistant-Tapo-Control#54] opened 2021-01-07 08:39 UTC
**Describe the bug**
The live stream on dashboard has 6 seconds of delay but some actions like motion detection is done in real time in dashboard and calling services like setting presets are done in real time in app camera but delayed in dashboard.  Moreover, if I use MotionEye inside HA, there's no such delay...it works like in app camera. So it isn't a problem of the camera or HA or raspberry. it seems engine used to play live stream in this integration.

**To Reproduce**
Just check this two images that I uploaded. Same environment (Raspberry PI 4 + hassio updated) inside HA with MotionEye or outside with rtsp.

![6 seconds delay-motion](https://user-images.githubusercontent.com/3323012/103870466-0ad1bc80-50cc-11eb-889a-6a5d83fb1af0.png)

![6 seconds delay](https://user-images.githubusercontent.com/3323012/103870389-ed9cee00-50cb-11eb-90fa-7b39ebcaf9c5.png)

**Expected behavior**
Just normal delay 1-2 seconds like in MotionEye Addon or playing via rtsp.

**Log**
No errors
**Camera (please complete the following information):**
 - Device Model: C.200
 - FW:1.0.17

**Using stream component**
[yes/no]

**Camera works through onvif component OR different cameras work in general**
yes

**Camera has all attributes filled out properly in developer tools**
yes

**HASS Environment**
Docker
**Additional context**
I know there was a bug to this, https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/37, but it isn't a problem of the camera or environment because inside HA, with MotionEye or out with rtsp directly it is working nicely. It is a  bit frustrating to have to wait 6 seconds to see motion detection sensor images, for example. Any chance to be able to change this behaviour ? I don't know how internally works this component, but any possibility to be able to do same as in MotionEye ?
Thanks for all your nice job JurajNyiri!

**Comment by JurajNyiri** [comment] 2021-01-07 14:31
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/37 .

**Closed by JurajNyiri** 2021-01-07 14:31 UTC
Labels: bug

**Comment by JurajNyiri** [comment] 2021-01-13 17:01
Version 2.4 has now been released addressing this, might provide significantly shorter delay for some users.

**Comment by jpcozar** [comment] 2021-01-13 18:45
Thank you JurajNyiri!
I just tried it and It works like a charm. That's exactly what I meant :-)
Now I can move my camera going to presets in real time and motion detection is synced with image.  
Thank you very much for this nice integration !
