### ISSUE TITLE
Configuration failed: D230

### ISSUE THREAD

**Issue by mschae** [JurajNyiri/HomeAssistant-Tapo-Control#464] opened 2023-11-18 16:44 UTC
### Description

After adding the D230 doorbell via the H200 hub I get configuration error. The flow for adding the camera works fine.

The error is:

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:770
Integration: Tapo: Kamerasteuerung (documentation, issues)
First occurred: 17:27:09 (19 occurrences)
Last logged: 17:38:12

Unable to connect to Tapo: Cameras Control controller: 'bool' object is not subscriptable

<img width="713" alt="grafik" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/473241/08b30fb0-e131-4974-91cf-663c7e0607b3">

### Reproduction Steps

1. Add camera using the GUI flow
2. Navigate to Devices
3. List Tapo Camera Control devices

### Expected behavior

Camera should be configured.

### If applicable, add error logs.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:770
Integration: Tapo: Kamerasteuerung (documentation, issues)
First occurred: 17:27:09 (19 occurrences)
Last logged: 17:38:12

### Device Firmware

Hub: 1.2.23 Build 20231012 rel.69638, Doorbell: 1.1.12 Build 20230809 rel.73260

### Integration Version

5.4.8

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

K3S on Server

### Search for similar issues

Yes

**Comment by mschae** [comment] 2023-11-18 16:46
Potentially related to / a dupe of #455

**Comment by JurajNyiri** [comment] 2023-11-18 20:32
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/455.

**Closed by JurajNyiri** 2023-11-18 20:32 UTC
