### ISSUE TITLE
Feature Request: Night Mode Sensor Entity

### ISSUE THREAD

**Issue by monstermuffin** [JurajNyiri/HomeAssistant-Tapo-Control#647] opened 2024-07-30 09:12 UTC
**Is your feature request related to a problem? Please describe.**
I have 2 outdoor cameras, one of them faces into a street lamp as as a consequence, night mode is not ever enabled when it should be. The other camera does not have this issue, so I would like to create an automation to be able to turn on/off night mode on one camera based on the other.

**Describe the solution you'd like**
I would like a sensor entity that reports whether or not night mode is currently enabled on the camera (outside of the night vision on/off/auto setting). If I am able to read the status of night mode on the cameras I can create an automation based on it.

**Additional context**
I'm not sure if this reporting is possible, but if it is then this would solve an issue for me and I'd hazard be a generally useful sensor entity. 

Thanks :)

**Comment by JurajNyiri** [comment] 2024-07-31 15:42
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/380

**Closed by JurajNyiri** 2024-07-31 15:42 UTC
