### ISSUE TITLE
Battery sensor unavailable (Tapo C420)

### ISSUE THREAD

**Issue by Pippo1989** [JurajNyiri/HomeAssistant-Tapo-Control#505] opened 2024-01-23 12:45 UTC
### Description

Hi,

since the last update, the battery sensor and several other memory-related sensors have become consistently unavailable (see attached image).

The problem occurs on Tapo c420 cameras.

### Reproduction Steps

/

### Expected behavior

The sensors described above should be available.

### If applicable, add error logs.

[home-assistant_tapo_control_2024-01-23T12-35-21.657Z.log](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/14025269/home-assistant_tapo_control_2024-01-23T12-35-21.657Z.log)

![Unavailable entities](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/70734f66-3fb3-470a-9999-35504269ac14)
-21.657Z.log)

### Device Firmware

1.2.15 Build 20231013 rel.73743

### Integration Version

5.4.14

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HASSIO on Raspberry Pi 4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment] 2024-01-23 13:03
Please fix the link to logs. Also try migrating back to previous version to confirm the issue is caused by the update.

**Comment by Pippo1989** [comment] 2024-01-23 14:39
> Please fix the link to logs. Also try migrating back to previous version to confirm the issue is caused by the update.

Done! But...

Something unexpected happened with the previous version (5.4.13): the battery level sensor disappeared... it doesn't even appear among the hidden entities.

**Comment by Exelord** [comment] 2024-02-11 21:20
Can confirm the issue

**Comment by JurajNyiri** [comment] 2024-03-02 08:39
I checked the logs for SD card as well as tapoBatterySensor entities, and they are added properly according to logs. So there must be some other error going on which I can't really tell from the logs.

Does this happen consistently - it never comes up?

**Comment by Pippo1989** [comment] 2024-03-23 06:43
Hi,

yes, I can confirm that the battery sensor is completely absent and does not appear among the camera entities.

**Comment by perdimia** [comment] 2024-03-29 21:07
I have lost the battery sensor on my doorbell

**Comment by vargabp** [comment] 2024-04-13 14:36
Had came to terms with it thinking a feature was removed, until stumbling across this. Having the same issue. It used to work, but can't tell when it stopped (have been using the entity in a dashboard monitoring battery levels for all devices).

**Comment by JurajNyiri** [comment] 2024-05-09 22:15
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.18.

**Closed by JurajNyiri** 2024-05-09 22:15 UTC
Labels: Help wanted
