### ISSUE TITLE
Floodlight and Whitelight does not set supported Color modes

### ISSUE THREAD

**Issue by patricknitsch** [JurajNyiri/HomeAssistant-Tapo-Control#562] opened 2024-04-24 08:12 UTC
### Description

The bug will be shown after Restart of HA.

### Reproduction Steps

Restart HA
Go to System, Protocol
See the warnings

### Expected behavior

Fix the bug

### If applicable, add error logs.

`Logger: homeassistant.components.light
Quelle: components/light/__init__.py:1272
Integration: Licht (Dokumentation, Probleme)
Erstmals aufgetreten: 06:17:31 (3 Vorkommnisse)
Zuletzt protokolliert: 06:17:31

None (<class 'custom_components.tapo_control.light.TapoFloodlight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues
None (<class 'custom_components.tapo_control.light.TapoWhitelight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues
`

### Device Firmware

1.3.11

### Integration Version

5.4.17PSA

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on Proxmox

### Search for similar issues

Yes

**Comment by tjorim** [comment] 2024-04-28 14:17
Duplicate of #530.

**Closed** 2024-04-28 14:18 UTC
