### ISSUE TITLE
Feature Request: Person detection

### ISSUE THREAD

**Issue by lesbass** [JurajNyiri/HomeAssistant-Tapo-Control#204] opened 2022-09-30 12:57 UTC
**Is your feature request related to a problem? Please describe.**
With the latest firmware updates, my C210 is able to tell if a motion is caused by a person or not. 
Using the official App, I can identify the motion caused by a person from the generic motions (things)

**Describe the solution you'd like**
I would like to have a secondo binary sensor for people motion detection

**Describe alternatives you've considered**
I went through the code but could not identify where to start to understand how to possibly add this feature

**Comment by JurajNyiri** [comment] 2022-09-30 12:59
If possible, this will first need to be discovered and added to [pytapo](https://github.com/JurajNyiri/pytapo/pull/31) library. 

Until that happens, this is impossible to implement here.

**Comment by vingerha** [comment] 2022-10-22 07:15
My 2 cents, Tapo already offers this (yes...at a price) but there are other free 3rd party solutions that can support this too and probably much better as this is what they were built and supported for, e.g. DOODS/Frigate/Deepstack

**Comment by vingerha** [comment] 2022-12-13 11:50
The question here is...will the Tapo integration be any better if doods/tensorflow (I am using deepstack btw) are not good enough. Why repeat the work someone else already did with high effort and further maintenance. Not saying that it is not possible, just doubting effort vs. gain

**Comment by slhad** [comment] 2022-12-13 13:03
I will try deepstack ! Still having less cpu consumed by doods or other 3rd party solutions if the results are similar, I will take it.

Having it working with the Tapo integration is simpler for people wanting to test it out in HA without requiring the extra installation/container for deepstack/doods

**Comment by slhad** [comment] 2022-12-13 15:02
Maybe I am wrong but seeing from the option of the Tapo app on Android, there is no need to add AI software and configure it, it just Camera options setup to allow Tapo "AI" to work on images and send notifications, please excuse me for the French screenshots,


![Screenshot_20221213-155646_Tapo](https://user-images.githubusercontent.com/4113601/207367932-ce1eb5ad-dbb8-4f4e-a6b2-d944d5deddea.png)
-> 
![Screenshot_20221213-155654_Tapo](https://user-images.githubusercontent.com/4113601/207367966-33615b3c-0e13-4d47-9db6-831dc596d55a.png)
-> 
![Screenshot_20221213-155757_Tapo](https://user-images.githubusercontent.com/4113601/207367997-01a549f6-74b6-46aa-863c-7ff18d3b0747.png)

**Comment by vingerha** [comment] 2022-12-13 15:09
aha... I thought this was part of the cloud offering.... so taking back my comments ....good to know this and then YES, would be great if this is an option too.

**Comment by lesbass** [comment] 2022-12-13 15:13
Yes, I confirm that on my C210 it's a free option, while on the C200 it's a paid option. Don't know why, but it would be nice to have access to that data on my C210, if it is possible.

**Comment by vingerha** [comment] 2022-12-13 15:18
I have a c310...I can switch it on and it indeed detects me-as-a-person but to receive 'rich' notifications ...then the paying starts.
I would already be happy to know that a person was detected.
Tools like deepstack allows to play round a bit more and detect 'me' or my kids. It also detects cat (although sometimes mistaken for dog). My learning: donot make it overcomplex...so this Tapo trick may indeed be good :)

**Comment by slhad** [comment] 2022-12-13 15:21
I have a C200 and don't have the Tapo Care thing (paid) and have activated the option but don't have alerts enabled as I use H.A with the camera feed and Doods for now but had seen that for some reason some options have to be enabled to work with the integration.

So maybe C200 as it for free for France ? And as I was wrinting, I from @vingerha that the 'rich' notifications are the pay part.
Would be happy with just person detection boolean as I am monitoring a bed with it :D

**Comment by lesbass** [comment] 2022-12-13 15:28
my use case is: I have a small office room with a Neato vacuum cleaner and I would like the vacuum to run every night only if a person has been detected in the room during the day (or every few days if no one is around). So, in my case, a generic person detection sensor would be enough :)

**Comment by lrlunin** [comment] 2023-08-01 21:44
> Yes, I confirm that on my C210 it's a free option, while on the C200 it's a paid option. Don't know why, but it would be nice to have access to that data on my C210, if it is possible.

Hi, I have just bought C200 in Germany and have the "person detection" feature for free. It works pretty well!

So to have this feature in HA we still need to implement this in pytapo, right?

**Comment by JurajNyiri** [comment] 2023-08-07 22:04
Closing as duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304 .

**Closed by JurajNyiri** 2023-08-07 22:04 UTC
Labels: Help wanted
