### ISSUE TITLE
Feature Request: making PERSON DETECTION entity actually working for TAPO C420 cameras + adding "PET DETECTION" and "VEHICLE DETECTION".

### ISSUE THREAD

**Issue by Pippo1989** [JurajNyiri/HomeAssistant-Tapo-Control#275] opened 2023-01-10 09:18 UTC
**Is your feature request related to a problem? Please describe.**
I think this issue should be considered more as a feature request than a real bug. In Tapo C420 cameras (integrated in Home Assistant), the "person detection" entity won't work: selecting between high, medium, low or off will result in a "error_code" response from Home Assistant. I think it is probably related to the different operating framework of this kind of cameras, since the actual options (from Tapo app) are (traslating to English): "Person Detection", "Pet Detection" and "Vehicle Detection", which are all under the "AI Detection" option.

**Describe the solution you'd like**
I'd like to be able to make the "Person Detection" entity actually working in my Home Assistant automations, and, if possibile, "Pet Detection" and "Vehicle Detection" entities too - which, at the moment, does not exist in the integration.
Of course, I should also be able to set a value from 1 to 10 for these entities, instead of "high", "medium", "low".

**Describe alternatives you've considered**
Nothing.

**Additional context**
Nothing.

**Comment by JurajNyiri** [comment] 2023-01-10 09:56
@fredrikhaggbom in order to support this we need to rewrite the function inside pytapo to use executeFunction instead of direct setter. 
Example changes like this in the past: https://github.com/JurajNyiri/pytapo/commit/e3fb586d92c8ca53d11750222fb393cf1c9f2f07
https://github.com/JurajNyiri/pytapo/commit/6acee4c0427111d0c4b6776b704ee07d881a02d7

I would do this myself but I do not have camera that supports this functionality at all so I cannot verify the change working with the new function call.

Once we make this change it will also work for battery powered cameras.

Could you please look into this?

**Comment by JurajNyiri** [comment] 2023-01-10 09:59
Once we have the original call working on normal cameras working transformed, someone will need to grab the actual call for pet/person etc detection like described in OP.
Is this something @bebo-bot-dev you could help us with please?

**Comment by fredrikhaggbom** [comment] 2023-01-10 20:40
@JurajNyiri I've created PRs in this project and pytapo with changes according to the conversation above.
I only have access to a camera with person detection support, and is therefore unable to investigate the calls to the other "AI functions" (pet, vehicle and baby i think is available?).

Regarding the "1-10" vs "low, medium, high", I've also thought about that. The person detection select is using the same options as the motion detection for concistency (i.e. "low, medium, high"), but I guess this can be changed to 1-10 as well for better granularity.

**Comment by jimmyz5150** [comment] 2023-07-21 23:56
One thing I noticed on c310 is that I can't get a trigger alarm for person detection only a select of high low norm. Only works if motion activated. I guess only binary sensor for motion detect? would be great to have that for person detect binary

**Comment by JurajNyiri** [comment] 2023-08-07 22:05
Closing as duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304 .

**Closed by JurajNyiri** 2023-08-07 22:05 UTC
Labels: Help wanted
