### ISSUE TITLE
Bug: Attribute privacy_mode reported on even if privacy mode is off

### ISSUE THREAD

**Issue by monotonus** [JurajNyiri/HomeAssistant-Tapo-Control#97] opened 2021-07-30 12:09 UTC
**Describe the bug**
I have a template sensor which tracks the camera attribute "privacy_mode" in order to use it in some automations. But the last days switching the camera off when coming home with the condition privacy_mode = off doesn't work because it's still reported as "on", but I can see the camera view.

The camera is rebooted automatically every night.

**To Reproduce**
Open a camera with active stream and view the attribute if it's reported on or off. Should be off.

**Expected behavior**

**Log**
no logs available

**Camera (please complete the following information):**
 - Device Model: C200
 - FW: 1.18 Build 210425 Rel.66776n(4555)

**Using stream component**
yes

**Camera works through onvif component OR different cameras work in general**
yes

**Camera has all attributes filled out properly in developer tools**
access_token: *************************************
model_name: C200
brand: TP-Link
motion_detection: on
device_type: SMART.IPCAMERA
device_model: C200
device_name: C200 1.0
device_info: C200 1.0
hw_version: 1.0
sw_version: 1.1.8 Build 210425 Rel.66776n(4555)
device_alias: tapo_camera
features: 3
barcode: 
mac: 60-32-B1-*******************
dev_id: 8021*************************************6E6167
oem_id: 890***********************************839C2
hw_desc: 4857*************************************000000001
user: administrator
motion_detection_sensitivity: normal
privacy_mode: on
alarm: off
alarm_mode: light
led: on
day_night_mode: auto
auto_track: on
presets: 
'1': kueche
'2': wand
'3': sofa
'4': esszimmer

friendly_name: tapo_camera - HD
icon: mdi:cctv
entity_picture: /api/camera_proxy/camera.tapo_camera_hd?token=***********************
supported_features: 3

**HASS Environment**
Version | core-2021.7.2
Installationstyp | Home Assistant Container

**Additional context**

**Comment by monotonus** [comment] 2021-07-30 12:15
Update: I've seen that the time was also out of sync. So I just reloaded the tapo integration in home assistant and all is working fine again.

So the problem is somewhere else.

**Comment by JanZimmer** [comment] 2021-09-08 07:14
I can confirm the behavior. Same camera model.
A reboot of the camera doesn't resolve the issue. A reload of the integration, as already described above, does resolve it.

In my opinion, this indicates an issue within the integration.

**Comment by JanZimmer** [comment] 2021-09-08 07:19
Additionally, after a reload, the video stream is missing which effectively forces me to reboot the whole hass instance.

**Comment by timothygee** [comment] 2021-11-25 03:46
I am also seeing this issue for my C200
When it happens I can't set the privacy mode because it is always on and therefore home assistant is always trying to turn it off

**Comment by JurajNyiri** [comment] 2021-12-13 23:30
I have not been able to replicate this, but have been keeping an eye on it. Actually I have both automations and lovelace condition cards set up according to privacy mode and it's been flawless. I did not update my cameras for a long time now so that might be a factor. 

I think it might be a combination of both some issue in camera and recovery of integration on failures. 
Integration recovery failure is indicated by reloading an integration solving it.
Issue with camera is indicated by 406 on stream. What is happening there, is integration (in case of stream enabled) just providing rtsp link to Home Assistant, nothing else. Maybe rebooting the Home Assistant instance frees up camera resources. I think I saw 406 when I had too many streams opened at once, or camera just decided to bug out.

In a current state this is very hard for me to debug. I will leave this opened in case someone who can both experience the issue and debug (and fix?) comes by.

**Comment by nialfrancis** [comment] 2022-01-18 07:48
I'm trying a few things with this as I had the issue with 1 camera. I suspect it is coming from the `hass.async_add_executor_job(controller.getPrivacyMode)`.

**Comment by markbooth73** [comment] 2022-10-20 12:27
Same here for me, can activate privacy mode, toggle but cannot de-activate, only from the TAPO APP

**Comment by JurajNyiri** [comment] 2022-10-20 22:31
Closing this issue. If anyone is still encountering non-functional switch for privacy mode reopen new issue.
If testing for any issues, make sure to:
1. Close Tapo app
2. Close any other application using streams from camera
3. Reboot Home Assistant
4. Reboot camera
5. Watch stream while switching privacy toggle. It is normal if it comes back to previous state as camera is not fast to report new changes and it might report old, but, eventually it should switch and update to correct state.

**Closed by JurajNyiri** 2022-10-20 22:31 UTC
Labels: Help wanted
