### ISSUE TITLE
Bug: Detected I/O inside the event loop - video stream not showing

### ISSUE THREAD

**Issue by pr0fetul** [JurajNyiri/HomeAssistant-Tapo-Control#13] opened 2020-10-06 12:56 UTC
**Describe the bug**
Detected I/O inside the event loop

**To Reproduce**
Installed from the repository the custom component, added the TAPO camera, it presents in HA the 2 devices HD and SD - but none are working - none are streaming

**Expected behavior**
No video stream is presented

**Log**
Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 3:46:26 PM (17 occurrences)
Last logged: 3:46:29 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tapo_control doing I/O at custom_components/tapo_control/camera.py, line 158: self._privacy_mode = self._controller.getPrivacyMode()['enabled']
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tapo_control doing I/O at custom_components/tapo_control/camera.py, line 164: alarmData = self._controller.getAlarm()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tapo_control doing I/O at custom_components/tapo_control/camera.py, line 174: self._led = self._controller.getLED()['enabled']
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tapo_control doing I/O at custom_components/tapo_control/camera.py, line 180: self._auto_track = self._controller.getAutoTrackTarget()['enabled']
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tapo_control doing I/O at custom_components/tapo_control/camera.py, line 189: self._attributes['presets'] = self._controller.getPresets()

**Camera (please complete the following information):**
Device info
C200
by TP-Link
Firmware: 1.0.14 Build 200720 Rel.38552n(4555)

**Additional context**

**Comment by pr0fetul** [comment] 2020-10-06 13:19
Also, if it's helpful, here is another error log regarding the stream:

```
Log Details (ERROR)
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:65
Integration: Stream (documentation, issues)
First occurred: 4:11:28 PM (5 occurrences)
Last logged: 4:12:55 PM

Stream connection failed: rtsp://user:password@192.168.0.142:554/stream2
Stream connection failed: rtsp://user:password@192.168.0.142:554/stream1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'rtsp://user:password@192.168.0.142:554/stream2'; last error log: [tcp] Port missing in uri
```

**Comment by JurajNyiri** [comment] 2020-10-06 13:24
Thank you for your bug report, I will take a look into it.

I see 2 issues here:
- Detected I/O inside the event loop
- Stream connection failed

I think I know how to fix the 1st.

- Does your rtsp stream work via VLC for example? rtsp://user:password@192.168.0.142:554/stream2 or stream1
- Is your camera turned on and responding on the ip? Can you control it via the app?
- Can you use some of the services on the camera and do they work? For example turning on and off the LED?

**Comment by pr0fetul** [comment] 2020-10-06 13:37
For the second issue, in VLC when I load either of the streams I get the Privacy Mode is on - which is true - and when I set the Privacy Mode to off from the mobile app, I get the normal video feed in VLC. In HomeAssistant it's only a black screen. 
I can control the camera from the mobile app without any issue. 
The Tapo integration created only 2 entities: Kitchen Camera - HD and - SD - none of the streams work. 
Using the services turn on or off - do not work, and taking a picture might work, but I did not give permissions for /tmp/ folder. 
The attributes for the HD one - similar with SD one are below:

```
access_token: xxxxxxxx
model_name: C200
brand: TP-Link
motion_detection: 'on'
device_type: SMART.IPCAMERA
device_model: C200
device_name: C200 1.0
device_info: C200 1.0
hw_version: '1.0'
sw_version: 1.0.14 Build 200720 Rel.38552n(4555)
device_alias: Kitchen Camera
features: '3'
barcode: ''
mac: D8-47-32-xx-xx-xx
dev_id: 802118F2626257AA505720D5ACD232871CFAD4F6
oem_id: 8902D2F34FCE407721DE92F5759839C2
hw_desc: '48574445534300000000000000000001'
motion_detection_sensitivity: normal
privacy_mode: 'off'
alarm: 'off'
alarm_mode:
  - sound
led: 'on'
auto_track: 'off'
presets:
  '1': Marked Position 1
  '2': Marked Position 2
friendly_name: Kitchen Camera - HD
icon: 'mdi:cctv'
entity_picture: >-
  /api/camera_proxy/camera.kitchen_camera_hd?token=xxxxxxxxxxxxx
supported_features: 2
```

**Comment by pr0fetul** [comment] 2020-10-06 13:56
I can confirm that this control works:
tapo_control.set_privacy_mode
entity_id: camera.kitchen_camera_hd
privacy_mode: on/off

I have just tested it - :( I am sorry - I did not realize it will expose tapo as services instead of camera - but it works - still no video stream :(

**Comment by JurajNyiri** [comment] 2020-10-06 14:34
Thank you, could you please provide more information about the environment you are running hass in? 
OS, python version etc so that I can try and replicate this

**Comment by pr0fetul** [comment] 2020-10-06 14:41
Sure. 
```
arch | x86_64
-- | --
chassis |  
dev | false
docker | true
docker_version | 18.09.8
hassio | true
host_os |  
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 3.10.105
python_version | 3.8.5
supervisor | 245
timezone | Europe/Bucharest
version | 0.115.6
virtualenv | false

```

**Comment by JurajNyiri** [comment] 2020-10-06 19:38
Fixed in [2.0.2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/2.0.2)

The issue is camera stream only worked if you were using "stream" component which I think you didn't. Now it works even without it.

Thank you for your bug report!

If it still does not work or you encounter any other bug please open a new issue.

**Comment by JurajNyiri** [comment] 2020-10-06 19:45
I just noticed your error was indeed coming from the stream component which meant you are using it.

Please test camera in 2.0.2 and let me know if it works.

If it doesn't, try without stream, see if that helps and let me know.

If everything works correctly please close this issue.

**Comment by pr0fetul** [comment] 2020-10-07 06:13
Good morning, 
I updated via HACS the component to the latest version. I restarted HA, but unfortunately the same issue - 
```
Log Details (ERROR)
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:65
Integration: Stream (documentation, issues)
First occurred: 8:06:01 AM (10 occurrences)
Last logged: 9:12:34 AM

Stream connection failed: rtsp://homeassistant:QwEr!2#4@192.168.0.142:554/stream2
Stream connection failed: rtsp://homeassistant:QwEr!2#4@192.168.0.142:554/stream1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'rtsp://homeassistant:QwEr!2#4@192.168.0.142:554/stream2'; last error log: [tcp] Port missing in uri
```
This is logged when I click on either the SD or HD component.

**Comment by JurajNyiri** [comment] 2020-10-07 08:57
1. Please try to set up camera via onvif and see if that works
2. Remove "stream:" from your configuration.yaml, see if that works
3.) Are any other cameras not from tapo working?

**Comment by pr0fetul** [comment] 2020-10-07 09:18
1. It seems I cannot set it up via Onvif integration - after inserting host IP, I get to inserting user/pass - and it states Unknown Error occured - and I cannot proceed further
2. I searched all my config files - I do not have stream declared anywhere
3. I  have 4 other TP-Link Spot Cameras - but they do not have stream capabilities like TAPO

**Comment by JurajNyiri** [comment] 2020-10-07 09:22
1. Make sure [to use port](https://www.tp-link.com/uk/support/faq/2680/) 2020 for onvif, if there is still error check logs
2. That is really weird, it should be using mjpeg stream in that case... try adding it
3. Then we need to test this camera via onvif or generic_camera to see if this is an issue of this integration or your setup

**Comment by pr0fetul** [comment] 2020-10-07 09:55
ok, I added the camera via Onvif - thank you for mentioning the port - I managed to add it. 
I added the  stream: into my configuration.yaml
Unfortunately even if the Onvif created the 2 devices, I cannot see the stream - the same error as above is present in the logs:
```
Log Details (ERROR)
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:65
Integration: Stream (documentation, issues)
First occurred: 12:43:08 PM (10 occurrences)
Last logged: 12:47:08 PM

Stream connection failed: rtsp://user:pass@192.168.0.142:554/stream2
Stream connection failed: rtsp://user:pass@192.168.0.142:554/stream1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'rtsp://user:pass
![config](https://user-images.githubusercontent.com/17175289/95316279-4629d880-089c-11eb-86b4-dcdeda4baedf.JPG)
![lovelace](https://user-images.githubusercontent.com/17175289/95316282-46c26f00-089c-11eb-9101-62f754367cb8.JPG)
![lovelace 2](https://user-images.githubusercontent.com/17175289/95316283-475b0580-089c-11eb-8508-2dd8a399a356.JPG)
![tapo integr](https://user-images.githubusercontent.com/17175289/95316286-475b0580-089c-11eb-870b-4fedf124faa4.JPG)
![onvif](https://user-images.githubusercontent.com/17175289/95316288-47f39c00-089c-11eb-92c4-fca240bb6730.JPG)




@192.168.0.142:554/stream2'; last error log: [tcp] Port missing in uri

```

**Comment by JurajNyiri** [comment] 2020-10-07 10:00
Onvif also not working indicates an issue with your setup and not this component.

Try to search and resolve your issue in the setup, the onvif is an official integration and should be always working. 

I think it will relate to a problem with ffmpeg version or av or something like that, not sure, didn't search too much.

Closing this issue as it is not related to this component.

If you encounter any other issue in the future please open a new issue.

**Comment by pr0fetul** [comment] 2020-10-07 11:30
Hi, sorry to bother again. I removed both integrations - Onvif and Tapo - restarted HA. I did the Onvif integration first - added the 2 components - and voila - now Onvif works. 

![onvif](https://user-images.githubusercontent.com/17175289/95324957-2fd64980-08a9-11eb-96c1-9d607c969939.JPG)

Then I added the TAPO integration - it added the 2 components - but no video stream :( - just like before

**Comment by JurajNyiri** [comment] 2020-10-07 11:40
To proceed further I would need to reproduce the bug (which I am not able to) or try out a few things on your environment to debug. I added you on hangouts if you are willing to share your screen.

**Comment by pr0fetul** [comment] 2020-10-07 11:43
I can help with debugging, but not right now as I am during working hours . After 7pm (EEST time) we can do a screen share on  teamviewer maybe.

**Comment by JurajNyiri** [comment] 2020-10-07 11:47
That works for me, lets meet at 7pm (EEST time). Teamviewer will be very useful for debugging 👍

**Comment by JurajNyiri** [comment] 2020-10-07 18:51
Hello, are you available for debugging?

**Comment by JurajNyiri** [comment] 2020-10-07 22:30
There was no meeting today as @pr0fetul didn't reach out.

I just checked the onvif integration and the code works exactly the same in this integration, meaning, it should either work on both, or none at all.

**Comment by pr0fetul** [comment] 2020-10-08 06:07
Hi,  I am sorry for that, I had some issues yesterday evening. Starting now I can get on TeamViewer for debugging. Please let me know when you are available and I will send you the credentials

**Comment by pr0fetul** [comment] 2020-10-08 13:00
I can enter remote if you can.

**Comment by JurajNyiri** [comment] 2020-10-08 14:23
Hello @pr0fetul once I finish 2.1 I will be able to help you. Add me on hangouts for easier communication please.

**Comment by pr0fetul** [comment] 2020-10-08 14:35
Ok, no hurry then. Unfortunately I do not have hangouts - I only use whatsapp - but you can text me here and I will send you the TV creds. At 7 pm I need to go out (in 1 and a half hours) - if we cannot connect by then, then I will return and contact you back.

**Comment by pr0fetul** [comment] 2020-10-08 14:48
Good news - dunno why, but now it works - all of a sudden.
The only thing I did recently (this morning) - I updated HA to 116. And now both streams HD and SD from both TAPO and Onvif work and are viewable. 
I do not know why but it works.

**Comment by JurajNyiri** [comment] 2020-10-08 14:53
Awesome news!

**Closed by JurajNyiri** 2020-10-08 14:53 UTC
Labels: bug
