### ISSUE TITLE
Most Controls not working in C120 camera

### ISSUE THREAD

**Issue by gorkang** [JurajNyiri/HomeAssistant-Tapo-Control#714] opened 2024-11-27 10:55 UTC
### Description

The Manual Alarm Start, Manual Alarm Stop and Siren controls do not work in the C120 camera.

![image](https://github.com/user-attachments/assets/2a233bf4-a6b9-49d0-aab6-f7c0e4117bca)

Manual Alarm Start and Stop fail with error:

> Failed to perform the action button/press. Error: Parameter to get/do does not exist, Response: {"error_code": -40106}

Siren with: 

> Failed to perform the action siren/turn_off. Camera does not support triggering the siren.

The logs for Manual Alarms are attached below.

### Reproduction Steps

1. Go to Camera controls and click the toggle or PRESS button.

### Expected behavior

All controls should work.

### If applicable, add error logs.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:14:23 AM (12 occurrences)
Last logged: 10:45:25 AM

[546714422576] Unexpected exception
[546884344496] Unexpected exception
[546441065328] Unexpected exception
[546534842448] Unexpected exception
[546736082368] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
    await self.async_press()
  File "/config/custom_components/tapo_control/button.py", line 121, in async_press
    await self._hass.async_add_executor_job(self._controller.startManualAlarm)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 1714, in startManualAlarm
    return self.performRequest(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 621, in performRequest
    raise Exception(
Exception: Error: Parameter to get/do does not exist, Response: {"error_code": -40106}

### Device Firmware

1.2.2. Build 240905 Rel. 41780n

### Integration Version

5.8.0

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

supervised installation on Raspberry Pi 4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment] 2024-11-27 12:54
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/713

**Closed by JurajNyiri** 2024-11-27 12:54 UTC
