### ISSUE TITLE
Feature Request: Tapo C310 motion detection modes

### ISSUE THREAD

**Issue by CoYoNq** [JurajNyiri/HomeAssistant-Tapo-Control#105] opened 2021-09-14 15:33 UTC
This devices have 4 motion events detection modes. Motion detection, area intrussion, line crossing and tamper.
I notice the only one that its reported to HA is the motion one. The other ones are not readed in the integration.

Any way to make the other sensors appears as entities in HA?

**Comment by JurajNyiri** [comment] 2021-09-14 22:25
Motion detection is captured via ONVIF standard. AFAIK there is no documented API that would report these events. If anyone discovers it, it can be implemented into pytapo and then here.

**Comment by dankocrnkovic** [comment] 2022-04-05 19:57
What does it mean "Motion detection is captured via ONVIF standard"?
Is motion detected by ONVIF so camera motion zones are ignored?

**Comment by AnthonyKNorman** [comment] 2022-04-22 12:04
I would also very much like to see this added

**Comment by JurajNyiri** [comment] 2023-08-07 22:04
Closing as duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304 .

**Closed by JurajNyiri** 2023-08-07 22:04 UTC
Labels: Help wanted
