### ISSUE TITLE
Firmware 1.3.9: Incorrect Cloud credentials

### ISSUE THREAD

**Issue by doraess** [JurajNyiri/HomeAssistant-Tapo-Control#451] opened 2023-11-08 09:03 UTC
### Description

I get the "Invalid cloud password" message whet trying to configures a new Tapo Camera.
I had 3 Tapo cameras correctly configured until yesterday, when I installed the new release of the HA integration (5.4.2) and the new camera firmware (1.3.9). Since then, I follow all the steps (camera IP, camera account user/password), and all is correct until I put the cloud password. 
I have changed 3 times the TPLink password, it works in the Tapo app, but to does not work in the HA extension. It still does not work in the latest version (5.4.3)

### Reproduction Steps

1. Install  Tapo : Cameras Control extension
2. Reboot HA
3. Add new extension
4. Insert camera IP address
5. Insert camera account credentials (user/password)
6. Insert Cloud password ---> error "Invalid cloud password"

### Expected behavior

The cloud password should work, as it is working in the Tapo app

### Device Firmware

1.3.9 Build 231019 Rel.29120n(4555)

### Integration Version

5.4.3

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAssio Os in 

### Search for similar issues

Yes

**Comment by JeromeS68** [comment] 2023-11-08 09:16
Same issue here. Since updating firmware to 1.3.9, it's no longer possible to connect TAPO Cloud.

**Comment by bysimba** [comment] 2023-11-08 09:20
Same issue here

**Comment by Honza-F** [comment] 2023-11-08 09:29
Same issue here

**Comment by JurajNyiri** [comment] 2023-11-08 09:30
From what we know so far, camera incorrectly generates the new password for local verification and it takes time to get it work again. Factory reset camera, remove from Tapo app, add to Tapo app and it will work.

I cannot investigate more until I receive the update.

**Comment by JurajNyiri** [comment] 2023-11-08 09:55
If you are still experiencing issue and you are willing to port forward camera and share credentials so that I can debug further, reach out to me via juraj.nyiri@gmail.com. Maybe I can find something we can do so that we do not need to factory reset.

**Comment by nnoaks** [comment] 2023-11-08 11:15
Removing the camera from the app and adding it back does not solve the issue.
I am still experiencing the same issue with entering the Cloud.

**Comment by bigmoby** [comment] 2023-11-08 12:48
Hi @JurajNyiri , thanks! 
The factory reset solves! 🚀

**Comment by cooperaj** [comment] 2023-11-08 13:14
Will we still need to drop the camera from the app?

**Comment by JurajNyiri** [comment] 2023-11-08 13:17
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.4.

**Closed** 2023-11-08 13:16 UTC

**Comment by JurajNyiri** [comment] 2023-11-08 13:19
Please make sure to confirm the change working, I do not own camera with this firmware so I couldn't test directly.

@cooperaj @bigmoby @nnoaks @bysimba @Honza-F @JeromeS68  @doraess

**Comment by bysimba** [comment] 2023-11-08 13:23
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/75123159/4e24ff23-f54b-40b0-a6b1-7848c7efc6bf)
Now is ok only the name is different instead of the device we have the ip address

**Comment by bigmoby** [comment] 2023-11-08 13:24
Hi @JurajNyiri thanks a lot, I've just solved with a factory reset anyway I'll try asap this new release!

**Comment by nnoaks** [comment] 2023-11-08 13:31
Hi @JurajNyiri ,
I can confirm it works now. Thanks a lot for the solution!

**Comment by bigmoby** [comment] 2023-11-08 13:39
Hi @JurajNyiri , yes I confirm it works! Many many thanks! 🙏

**Comment by JeromeS68** [comment] 2023-11-08 14:02
Hi @JurajNyiri, it works now, thanx a lot !

**Comment by JeromeS68** [comment] 2023-11-08 14:39
Now my motion sensor is down... Marked as "no longer provided by the tapo_control integration".
Do you guys get same issue ?
I guess I will try factory reset.

**Comment by JurajNyiri** [comment] 2023-11-08 14:40
@JeromeS68 that is expected, no need to factory reset.

Read and follow https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#troubleshooting--faq

**Comment by JeromeS68** [comment] 2023-11-08 14:43
Ok, I will test it when I get back home. Thanks !

**Comment by bysimba** [comment] 2023-11-14 09:59
hello now we are in the same problem what you need to solve i can give Access to my cam

**Comment by aIexus** [comment] 2023-11-20 14:09
@JurajNyiri Hello!

I don't use Tapo Cloud Account, 
Camera C200, hardware version: 2.0, firmware: 1.3.9 Build 231019 Rel.38052n(4555).

Camera Control integration is reinstalled (latest , I reset camera to factory settings, created the 3rd party account - but it doesn't help.
What I should do to fix Incorrect Cloud credentials?
