### ISSUE TITLE
Camera tapo problem after update

### ISSUE THREAD

**Issue by sirector20** [JurajNyiri/HomeAssistant-Tapo-Control#372] opened 2023-07-26 18:07 UTC
### Description

I have a problem after update. Tapo camera in my system Unable to display images. by following the problem And not all my cameras can work at the same time. but a new camera that has never been used in the system but added after update can be used normally How should I fix it?

### Reproduction Steps

1.When I update I can't use all 7 cameras at the same time to view images in Home Assistant. or the ability to snap pictures to send notifications

2.When I remove the camera device and then add it back again can't do

3.But if adding camera equipment The new one that has never been used in the system can add three cars. and can be used normally

4.I have tried removing the camera. Reset the camera body to start the procedure all over again. but unable to add devices into the system

### Expected behavior

Images can be displayed normally.

### If applicable, add error logs.

Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.0.229:554/stream1
00:41:07 – (ERROR) Stream - message first occurred at 00:27:59 and shows up 13 times
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.0.6:554/stream1
00:41:07 – (ERROR) Stream - message first occurred at 00:27:59 and shows up 13 times
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.0.4:554/stream1
00:41:07 – (ERROR) Stream - message first occurred at 00:27:59 and shows up 13 times
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.0.3:554/stream1
00:41:07 – (ERROR) Stream - message first occurred at 00:27:59 and shows up 13 times
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.0.7:554/stream1
00:41:07 – (ERROR) Stream - message first occurred at 00:27:59 and shows up 13 times

### Device Firmware

1.3.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

OS on intelNuc

### Search for similar issues

Yes

**Comment by sirector20** [comment] 2023-07-26 18:09
Logger: homeassistant.components.stream.stream.camera.cam_chans_ng_hd
Source: components/stream/__init__.py:434
Integration: Stream (documentation, issues)
First occurred: 00:27:59 (21 occurrences)
Last logged: 01:03:12

Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.0.6:554/stream1
Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.0.6:554/stream1

**Comment by JurajNyiri** [comment] 2023-07-26 19:07
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/371

**Closed by JurajNyiri** 2023-07-26 19:07 UTC
