### ISSUE TITLE
C200 preset not working

### ISSUE THREAD

**Issue by erikwachters** [JurajNyiri/HomeAssistant-Tapo-Control#381] opened 2023-08-12 18:32 UTC
### Description

Hi, I've set some presets in the Tapo APP and they appear in Home Assistant in the input_selestion box but when I select a preset the following message appears in the left lower corner of HA:
`Failed to call service select/select_option. Preset 1 is not set in the app.`

thx

### Reproduction Steps

1. Make presets in the Tapo APP
2. go to Settings
3. go to Devices and Services
4. Select the device under Tapo: Cameras Control
5. select a preset in selection box: Move to preset

### Expected behavior

Camera pan/tilt to the saved preset location

### Device Firmware

1.3.5 Build 230717 Rel.47395n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on Debian

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment] 2023-08-13 06:17
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/340 . Please try the steps there and continue discussion there.

**Closed by JurajNyiri** 2023-08-13 06:17 UTC

**Comment by JurajNyiri** [comment] 2023-08-21 09:17
I was able to replicate this and this is now fixed in [5.3.2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.2).
