### ISSUE TITLE
Bug: No Still Images and not Entities

### ISSUE THREAD

**Issue by RestOp** [JurajNyiri/HomeAssistant-Tapo-Control#20] opened 2020-10-08 08:12 UTC
Hello,

thanks for the try to make Tapo work with РФ!

What i have noticed:

1. Not preview images 
![image](https://user-images.githubusercontent.com/46259141/95432059-703bd300-094e-11eb-94ea-db0dae742b3c.png)

2. No entities was created as as written
![image](https://user-images.githubusercontent.com/46259141/95432211-a4af8f00-094e-11eb-9d51-f0acc2fe7f72.png)

The only two are camera entities. Or i have misunderstood the manual. Please let me know how to get this entities.
As was written, was perfect if there was a examples.

Thanks a lot!

**Comment by JurajNyiri** [comment] 2020-10-08 08:35
- Still images are coming in 2.1, not released yet.
- I will need to update readme there is a typo, currently it creates 2 camera entities and you can call tapo_control **services** on them.

**Comment by GSzabados** [comment] 2020-10-08 09:40
I just wanted to post the same, then waiting for 2.1!  👍

**Comment by JurajNyiri** [comment] 2020-10-08 12:43
Fixed in future release 2.1.

**Comment by JurajNyiri** [comment] 2020-10-08 12:44
As for examples (not covered in 2.1), this is duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/15 so can be closed as all the points are covered.

**Closed** 2020-10-08 18:52 UTC
Labels: Implemented in next release, bug, duplicate

**Comment by RestOp** [comment] 2020-10-08 19:54
No motion sensor was created after update 2.1
http://prntscr.com/uvpmcn
Even after motion detected, even after restart of HA.

Also i tried to delete inetrgration this way 
![image](https://user-images.githubusercontent.com/46259141/95506646-7793c880-09b0-11eb-8dbd-3d4623b3adba.png)


Nothing happened. But it maybe it normal behaviour for addons from hacs, i do not know.
Will try now delete from HACS and intall one more time.

**Comment by JurajNyiri** [comment] 2020-10-08 19:58
@RestOp Follow [troubleshooting](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#troubleshooting)

Also make sure the camera is not in privacy mode.

**Comment by RestOp** [comment] 2020-10-08 19:59
Not in privacy.
Oh sorry did not saw it!
Will try now! Thanks a lot!

**Comment by RestOp** [comment] 2020-10-08 20:09
After reinstallation sensor was created with new install of cam!
What is timeout of sensor? 4 Minites it shows me that motion silll detected, in spite of nobody on room and cam was rebooted
![image](https://user-images.githubusercontent.com/46259141/95508261-fdb10e80-09b2-11eb-88fa-15426922d162.png)

**Comment by JurajNyiri** [comment] 2020-10-08 20:14
It is updated by the camera, when camera decides there is no longer movement it turns it off.

You can try lowering the sensitivity.

The camera is a bit buggy when you don't properly unsubscribe (by killing hass for example and not shutting down) or sometimes just refuses to accept connections to events "because it doesn't feel like it".

Here is what has always worked for me while developing to get the camera to report the events correctly:
1. Reboot the camera, wait until the LED turns on to red color
2. As soon as the LED is red, restart Home Assistant

Give it a while and it will sort itself out... it would sort itself out even if you didn't do anything, it just takes some time.

**Comment by RestOp** [comment] 2020-10-08 20:33
Somwthing looks wrong by me.
I waited 18 minuted, still detected. 
Then made all steps you wrote. Detected.
And its still detected after restart 
![image](https://user-images.githubusercontent.com/46259141/95510522-58983500-09b6-11eb-9054-408c092f66b5.png)

**Comment by JurajNyiri** [comment] 2020-10-08 20:35
What is the camera type? Please open a new issue for this. I only tested C200 but I see no reason why it wouldn't work on C100.

**Comment by RestOp** [comment] 2020-10-08 20:58
I have C200
