### ISSUE TITLE
Feature Request: C500 support

### ISSUE THREAD

**Issue by jcorreaes** [JurajNyiri/HomeAssistant-Tapo-Control#308] opened 2023-04-08 17:50 UTC
**Is your feature request related to a problem? Please describe.**
C500 Tapo camera works like a charm, but no binary motion sensor is available.

**Describe the solution you'd like**
I have a C200 1.0 and a C200 2.0, and both work perfectly, but C500 1.0 is not showing a motion sensor on HA.

**Additional context**

Noise sensor is available, but seems not working on HA.

<img width="688" alt="Screenshot 2023-04-08 at 18 47 48" src="https://user-images.githubusercontent.com/4310/230735762-e60145f1-dd23-4665-82c4-37e6b5067cb2.png">
<img width="671" alt="Screenshot 2023-04-08 at 18 47 56" src="https://user-images.githubusercontent.com/4310/230735764-f938d9d3-6a9c-4be4-b7af-f5c4daaf7bc0.png">
<img width="708" alt="Screenshot 2023-04-08 at 18 48 04" src="https://user-images.githubusercontent.com/4310/230735770-07537f6a-8f88-4710-b531-4f12f3ebc66c.png">

**Comment by JurajNyiri** [comment] 2023-04-08 18:05
Is there any error in the logs? This is probably duplicate of https://github.com/home-assistant/core/issues/85902#issuecomment-1490120209 . Once it is fixed upstream it will be fixed also here.

**Closed by JurajNyiri** 2023-04-08 18:05 UTC
