### ISSUE TITLE
Unable to rotate cameras from script

### ISSUE THREAD

**Issue by banditoth** [JurajNyiri/HomeAssistant-Tapo-Control#785] opened 2024-12-21 08:00 UTC
### Description

When attempting to rotate the Tapo C210 camera via a script in Home Assistant, the camera intermittently fails to execute the requested rotation to the preset. 
The issue occurs approximately 50% of the time, suggesting potential inconsistencies in entity state validation or preset recognition within the integration.

### Reproduction Steps

1.	Create a script in Home Assistant that triggers the camera to move to a specific preset.
	2.	Ensure the target preset is valid and configured within the select.nappali_move_to_preset entity.
	3.	Execute the script multiple times.

### Expected behavior

The camera should consistently rotate to the requested preset without errors, provided the preset name is valid.

Actual:
The rotation request fails intermittently with the error message stating the preset is not valid, even though it is correctly configured and works at other times.

### If applicable, add error logs.

Error: Option BEJÁRAT ÉS KONYHA is not valid for entity select.nappali_move_to_preset, valid options are: 

### Device Firmware

1.13.4 build 240801 rel.64982n

### Integration Version

6.0.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

haos

### Search for similar issues

Yes

### Additional information

Camera model : C210

**Comment by banditoth** [comment] 2024-12-21 08:04
I’ve also resetted the cameras, and deleted the integration from HA, and readded it with fresh installs of the cams. It did not solved this problem

**Comment by banditoth** [comment] 2024-12-21 08:09
Thats my script:
![IMG_3018](https://github.com/user-attachments/assets/e2808f89-3b9a-48e8-bb30-c4cc7c230183)

**Comment by JurajNyiri** [comment] 2024-12-21 09:27
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/484 please continue there. I am having a hard time replicating this issue.

**Closed by JurajNyiri** 2024-12-21 09:27 UTC
