### ISSUE TITLE
Feature Request: add doorbell event support 

### ISSUE THREAD

**Issue by floriske** [JurajNyiri/HomeAssistant-Tapo-Control#737] opened 2024-12-09 19:13 UTC
**Is your feature request related to a problem? Please describe.**
At this moment doorbell events like e.g. "button pressed" or "chime rings" aren't available

**Describe the solution you'd like**
It would be great if the events could be added to the integration so they can be used for automations in HA

**Describe alternatives you've considered**
I tried creating a very small motion detection area  in surveillance station so I could mimick a button press event with the Synology integration but this still also detects motion further away so it doesn't work

P.s. and kind of offtopic but it's great to see that all of your efforts resulted in an update by tp-link so this integration will work again!

**Comment by JurajNyiri** [comment] 2024-12-09 19:40
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/397

There is currently no known api that would expose this. If it’s available via onvif events or an api is found it could be added.

**Closed by JurajNyiri** 2024-12-09 19:40 UTC
