### ISSUE TITLE
camera.snapshot doesn't work

### ISSUE THREAD

**Issue by Veda82** [JurajNyiri/HomeAssistant-Tapo-Control#246] opened 2022-10-29 18:41 UTC
### Description

camera.snapshot is not working. A file is created but its size is zero. Seems like:

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/180

Tried rebooting the camera from the Tapo App but the issue is still present. Also tried rebooting homeassistant.
ONVIF component gives the same result. Tried disabling stream component, nothing happens.

### Reproduction Steps

1. Go to SERVICES
2. Select Camera: Take Snapshot
3. Select Tapo C200 camera
4. Input desired file location (Filename)
5. Press CALL SERVICE

### Expected behavior

Image is saved properly.

### If applicable, add error logs.

No error logs are being generated.

### Device Firmware

1.1.19 Build 220627 Rel.33188n(4555) (latest release, updated yesterday)

### Using stream component

Yes

### Does camera work via official integrations?

No

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment] 2022-10-29 19:05
If onvif component does result in the same, the issue is not with this integration.
Closing.

**Closed** 2022-10-29 19:04 UTC

**Comment by Veda82** [comment] 2022-10-29 19:18
Sorry, but other people reported the same issue, saying that in the past was working.

Again, see: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/180

Seems a bit rude to close the issue without investigating a bit further...

Maybe something changed in homeassistant, If that is the case, maybe the integration needs to be updated.

I am more than willing to provide support by trying an updated version of the component.
