### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by acs-lux** [JurajNyiri/HomeAssistant-Tapo-Control#139] opened 2022-02-06 04:44 UTC
Implement Tapo Care features.

Tapo Care is a paid subscription service that reinstates auto tracking controllable in home assistant and also provides AI for person detection.

A binary sensor for person detection would be a very useful thing in home assistant. For example, this would mean there really is someone at the door.

Maybe there are other sensors too if you have Tapo Care.

**Comment by JurajNyiri** [comment] 2022-02-06 10:15
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/126 .

**Closed by JurajNyiri** 2022-02-06 10:15 UTC
