### ISSUE TITLE
RAM leak

### ISSUE THREAD

**Issue by Anth0ny29** [JurajNyiri/HomeAssistant-Tapo-Control#601] opened 2024-05-31 07:31 UTC
### Description

Hello! 

I've noticed that RAM usage on my RPi3b+ keeps increasing when using the TAPO integration for my C200 camera. I recently switched to a NUC thinking my Raspberry Pi was the problem, but the issue persists.

In the provided screenshot, the available RAM gradually decreases until it either causes my Raspberry Pi to restart or completely crash. After disabling the integration, the problem seems to have disappeared. 

Is this a known issue? 

I don't have any specific errors, except for some camera sensors taking more than 10 seconds to update.

![Screenshot_20240531-091009](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/43807800/c582aa80-d4db-4aa7-86ba-def866cdd849)

### Reproduction Steps

1 - Integrate C200 Tapo Camera with the integration
2 - Wait a few hours and see if the RAM usage goes up

### Expected behavior

No RAM leak

### Device Firmware

1.3.13  Build 240327 Rel.63336n(4555)

### Integration Version

5.4.13

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

RPI 3B+ and NUC

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment] 2024-05-31 08:27
Could you try disabling most of the features under integration options? Onvif, time sync etc to see if we can identify the area causing the leak.

**Comment by JurajNyiri** [comment] 2024-05-31 08:31
![IMG_1393](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/5785999/8c42d206-1a63-44d6-9014-6df06857b4dd)

I can see something similar on my system as well but I have not verified whether it’s caused by this integration or not.

**Comment by JurajNyiri** [comment] 2024-05-31 08:35
As a first step please keep it off for a longer period to definitely conclude it is caused by this integration as in your screenshot the without Tapo part is very short.

**Comment by Anth0ny29** [comment] 2024-05-31 08:42
I will disable the integration for a longer period, and I will get back to you when I have more information! 
I wanted to at least bring up the topic for investigation :)

**Comment by JurajNyiri** [comment] 2024-05-31 08:47
Thank you for that! I will try to investigate code in the meantime to see if I can find anything. If you find it is caused by Tapo, under configuration for the device under settings:

- Disable motion sensor 
- Disable webhooks
- Disable automatically sync time
- Disable sound sensor
- Disable media sync 

if the problem stops, start enabling again
If the problem does not stop, I know which areas are not causing the leak at least.  

Memory leaks are very hard to track down usually.

**Comment by Anth0ny29** [comment] 2024-05-31 21:09
Small Update: I left most of the day without the Tapo integration (until I launched a RAM profiler which crashed everything) and apparently the RAM continues to gradually increase. It does seem slower though, which might be why I thought it was caused by the plugin. 
So, I don't know if this is normal or not, and whether it's actually a problem in the end. Maybe everyone experiences this but after a while it goes down on its own (and my RPI3B+ was just limited with 1GB of RAM).
![Tapo disabled](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/43807800/ed449a17-6aaa-4beb-aaee-943940c48032)

**Comment by JurajNyiri** [comment] 2024-06-12 11:36
Hi @Anth0ny29 any luck in here? Can we close this or is this an issue?

**Comment by Anth0ny29** [comment] 2024-06-12 20:24
Hello! I wanted to wait and see in the long run, but apparently the RAM usage increases and then seems to stabilize after a while. Maybe my Raspberry Pi lacked RAM and the NUC can handle the RAM demand over the long term. I think we can close the topic. Anyway, thanks for looking into it :)

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/43807800/4fa52b88-08f6-4884-ba0f-d25783d0fc3a)

**Closed** 2024-06-12 20:32 UTC
