### ISSUE TITLE
Feature Request: Start/stop recording + Take Photo

### ISSUE THREAD

**Issue by nchieffo** [JurajNyiri/HomeAssistant-Tapo-Control#199] opened 2022-08-19 21:42 UTC
**Is your feature request related to a problem? Please describe.**
My feature request is related to the fact that I need to use the TAPO APP in order to start/stop a recording or take a photo

**Describe the solution you'd like**
I'd like to see some services or entities that allows me to
- start/stop a recording to the SD card
- take a photo to the SD card

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JurajNyiri** [comment] 2022-08-20 00:09
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/40

**Closed by JurajNyiri** 2022-08-20 00:09 UTC

**Comment by JurajNyiri** [comment] 2022-08-20 00:10
Recording to SD card is manage to by camera itself. There is no way how to manually start or stop recording via api
